#!/usr/bin/env python3
"""Generate per-variant run cards for every eval variant.

Reads results.json for each eval, generates a runcard-config.tex per variant,
builds the PDF, and collects all PDFs into data/run-cards/variants/.

Usage:
    python generate_variant_cards.py [--jobs N]
"""

from __future__ import annotations

import json
import shutil
import subprocess
import sys
from concurrent.futures import ProcessPoolExecutor, as_completed
from pathlib import Path
from typing import Any

EVALS: dict[str, dict[str, str]] = {
    "arc_challenge": {
        "results": "data/arc-workup/results.json",
        "display": "ARC Challenge",
        "source": "ai2\\_arc/ARC-Challenge",
    },
    "cybermetric_2000": {
        "results": "data/cybermetric/results.json",
        "display": "CyberMetric-2000",
        "source": "cybermetric\\_2000",
    },
    "mmlu_0_shot": {
        "results": "data/mmlu/results.json",
        "display": "MMLU (0-shot)",
        "source": "mmlu\\_0\\_shot (500-item subset)",
    },
    "hellaswag": {
        "results": "data/hellaswag/results.json",
        "display": "HellaSwag",
        "source": "hellaswag (500-item subset)",
    },
    "truthfulqa": {
        "results": "data/truthfulqa/results.json",
        "display": "TruthfulQA",
        "source": "truthful\\_qa (MC2, 500-item subset)",
    },
    "gsm8k": {
        "results": "data/gsm8k/results.json",
        "display": "GSM8K",
        "source": "gsm8k (500-item subset)",
    },
}

TEMPLATE_SRC = Path("templates/run-card/single-run-card/runcard.tex")
OUTPUT_BASE = Path("data/run-cards/variants")


def wilson_ci(k: int, n: int, z: float = 1.96) -> tuple[float, float]:
    if n == 0:
        return 0.0, 0.0
    import math

    p_hat = k / n
    denom = 1 + z * z / n
    center = (p_hat + z * z / (2 * n)) / denom
    margin = z * math.sqrt(p_hat * (1 - p_hat) / n + z * z / (4 * n * n)) / denom
    return max(0.0, center - margin), min(1.0, center + margin)


def generate_config(eval_name: str, meta: dict[str, str], variant: dict[str, Any]) -> str:
    vid = variant["variant_id"]
    acc = variant["accuracy"]
    n = variant["n_samples"]
    temp = variant.get("temperature", 0.0)
    seed = variant.get("order_seed", 0)

    if acc is not None and n > 0:
        k = round(acc * n)
        lo, hi = wilson_ci(k, n)
        width = hi - lo
        acc_str = f"{acc:.6f}"
        lo_str = f"{lo:.6f}"
        hi_str = f"{hi:.6f}"
        width_str = f"{width:.6f}"
    else:
        acc_str = ""
        lo_str = ""
        hi_str = ""
        width_str = ""

    eval_slug = eval_name.replace("_", "-")
    run_id = f"MOJAVE-2026-0519-{eval_slug.upper()[:8]}-{vid}"

    lines = [
        f"% Per-variant run card: {meta['display']} / {vid}",
        "% Auto-generated by generate_variant_cards.py",
        "",
        f"\\rcset{{run.id}}            {{{run_id}}}",
        "\\rcset{date.issued}       {2026-05-19}",
        f"\\rcset{{benchmark.name}}    {{{meta['display']}}}",
        "\\rcset{benchmark.version} {UK AISI Inspect Evals (2026-05)}",
        f"\\rcset{{benchmark.source}}  {{\\texttt{{{meta['source']}}}}}",
        "\\rcset{model.name}        {Qwen/Qwen2.5-7B-Instruct}",
        "\\rcset{model.revision}    {\\texttt{HuggingFace (default revision)}}",
        "\\rcset{model.quant}       {bf16 (no quantization)}",
        "\\rcset{model.serving}     {vLLM 0.8.5.post1, L4 24GB, max\\_tokens=4096}",
        "\\rcset{evaluator.org}     {antimeme.ai}",
        "\\rcset{evaluator.tool}    {UK AISI Inspect AI}",
        "",
        f"\\rcset{{n.items}}           {{{n}}}",
        f"\\rcset{{n.variants}}        {{1 (single variant: {vid})}}",
        f"\\rcset{{perturb.design}}    {{Single variant. "
        f"Temperature $T={temp}$, option-order seed {seed}.}}",
        f"\\rcset{{inference.config}}  {{temperature={temp}, order\\_seed={seed}, top\\_p=1.0}}",
        "",
        f"\\rcset{{acc.overall}}       {{{acc_str}}}",
        f"\\rcset{{wilson.lower}}      {{{lo_str}}}",
        f"\\rcset{{wilson.upper}}      {{{hi_str}}}",
        f"\\rcset{{wilson.width}}      {{{width_str}}}",
        f"\\rcset{{acc.baseline}}      {{{acc_str}}}",
        "",
    ]

    empty_fields = [
        "irt.model",
        "irt.diff.mean",
        "irt.diff.sd",
        "irt.diff.min",
        "irt.diff.max",
        "irt.diff.hist",
        "irt.disc.mean",
        "irt.disc.sd",
        "irt.disc.min",
        "irt.disc.max",
        "irt.disc.hist",
        "irt.disc.caveat",
        "irt.floor.items",
        "irt.ceil.items",
        "irt.nearzero.disc",
        "q3.summary",
        "q3.count.gt2",
        "q3.note",
        "stab.hist",
        "stab.stable",
        "stab.sensitive",
        "dim.order",
        "dim.temp",
        "dim.prompt",
        "dim.mixed",
        "spearman.diff.rho",
        "spearman.diff.lo",
        "spearman.diff.hi",
        "spearman.disc.rho",
        "spearman.disc.lo",
        "spearman.disc.hi",
        "sprt.method",
        "sprt.beta",
        "sprt.alpha",
        "sprt.nperm",
        "sprt.median.stop",
        "sprt.iqr.lo",
        "sprt.iqr.hi",
        "sprt.frac.q4",
        "sprt.frac.half",
        "sprt.frac.full",
        "companion.file",
        "companion.hash",
        "companion.contents",
    ]
    for field in empty_fields:
        lines.append(f"\\rcset{{{field}}}       {{}}")

    return "\n".join(lines) + "\n"


def build_pdf(work_dir: Path) -> tuple[str, bool, str]:
    """Build PDF in work_dir. Returns (name, success, message)."""
    name = work_dir.name
    try:
        for _ in range(2):
            r = subprocess.run(
                ["pdflatex", "-interaction=nonstopmode", "runcard.tex"],
                cwd=work_dir,
                capture_output=True,
                timeout=30,
            )
        if (work_dir / "runcard.pdf").exists():
            return name, True, ""
        else:
            return name, False, r.stderr.decode()[-200:]
    except Exception as e:
        return name, False, str(e)


def main() -> None:
    import argparse

    parser = argparse.ArgumentParser()
    parser.add_argument("--jobs", type=int, default=8)
    args = parser.parse_args()

    OUTPUT_BASE.mkdir(parents=True, exist_ok=True)

    work_dirs: list[Path] = []
    total = 0

    for eval_name, meta in EVALS.items():
        results_path = Path(meta["results"])
        if not results_path.exists():
            print(f"SKIP {eval_name}: {results_path} not found", file=sys.stderr)
            continue

        data = json.loads(results_path.read_text())

        for variant in data["variants"]:
            vid = variant["variant_id"]
            if variant["accuracy"] is None:
                continue

            eval_slug = eval_name.replace("_", "-")
            card_dir = OUTPUT_BASE / f"{eval_slug}-{vid}"
            card_dir.mkdir(parents=True, exist_ok=True)

            config = generate_config(eval_name, meta, variant)
            (card_dir / "runcard-config.tex").write_text(config)
            shutil.copy2(TEMPLATE_SRC, card_dir / "runcard.tex")

            work_dirs.append(card_dir)
            total += 1

    print(f"Generated {total} variant configs, building PDFs...", file=sys.stderr)

    done = 0
    failed = 0
    with ProcessPoolExecutor(max_workers=args.jobs) as pool:
        futures = {pool.submit(build_pdf, d): d for d in work_dirs}
        for future in as_completed(futures):
            name, success, msg = future.result()
            done += 1
            if not success:
                failed += 1
                print(f"  FAIL {name}: {msg}", file=sys.stderr)
            if done % 50 == 0 or done == total:
                print(
                    f"  {done}/{total} built ({failed} failed)",
                    file=sys.stderr,
                )

    print(f"\nDone: {done - failed}/{total} PDFs built", file=sys.stderr)


if __name__ == "__main__":
    main()
