// Build scripts panic on failure (correct behavior — a failed build
// should stop loudly), so the workspace's `unwrap_used` / `expect_used`
// lints don't apply here.
#![allow(clippy::unwrap_used, clippy::expect_used)]

//! Build script — parses the vendored Joe-Kuo direction-number
//! files at compile time and emits Rust constants. The resulting
//! `joe_kuo_d6_data.rs` is included by `src/sobol.rs` via
//! `include!(concat!(env!("OUT_DIR"), "/joe_kuo_d6_data.rs"))`.
//!
//! Format of the input files:
//!
//! ```text
//! d       s       a       m_i
//! 2       1       0       1
//! 3       2       1       1 3
//! 4       3       1       1 3 1
//! ...
//! ```
//!
//! - `d`: dimension index (starts at 2; dimension 1 is the special
//!   identity case handled in source).
//! - `s`: degree of the primitive polynomial.
//! - `a`: encoded coefficient bits (low-bit-first within `s` bits).
//! - `m_i`: `s` initial direction-number values.
//!
//! Each parsed row becomes a `JoeKuoD6Dim` constant. The two output
//! constants `JOE_KUO_D6_MINIMAL` (100 dims) and `JOE_KUO_D6_STANDARD`
//! (1000 dims) are emitted as `&'static [JoeKuoD6Dim]` slices.
//!
//! See `data/LICENSE.joe-kuo` for the BSD-3-Clause attribution.

use std::env;
use std::fs;
use std::io::Write;
use std::path::PathBuf;

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let data_dir = manifest_dir.join("data");

    let minimal = parse_file(&data_dir.join("new-joe-kuo-6.100"));
    let standard = parse_file(&data_dir.join("new-joe-kuo-6.1000"));

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let out_path = out_dir.join("joe_kuo_d6_data.rs");
    let mut out = fs::File::create(&out_path)
        .unwrap_or_else(|e| panic!("create {}: {e}", out_path.display()));

    writeln!(out, "// Auto-generated by build.rs — do not edit.").unwrap();
    writeln!(out).unwrap();
    emit_constant(&mut out, "JOE_KUO_D6_MINIMAL_DATA", &minimal);
    writeln!(out).unwrap();
    emit_constant(&mut out, "JOE_KUO_D6_STANDARD_DATA", &standard);

    // Re-run the build script if the data files change.
    println!(
        "cargo:rerun-if-changed={}",
        data_dir.join("new-joe-kuo-6.100").display()
    );
    println!(
        "cargo:rerun-if-changed={}",
        data_dir.join("new-joe-kuo-6.1000").display()
    );
    println!("cargo:rerun-if-changed=build.rs");
}

#[derive(Debug)]
struct JoeKuoDim {
    d: u16,
    a: u32,
    m: Vec<u32>,
}

fn parse_file(path: &std::path::Path) -> Vec<JoeKuoDim> {
    let content =
        fs::read_to_string(path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    let mut out = Vec::new();
    for line in content.lines() {
        // Skip the header line.
        if line.starts_with('d') {
            continue;
        }
        let mut tokens = line.split_whitespace();
        let Some(d_str) = tokens.next() else { continue };
        let d: u16 = d_str
            .parse()
            .unwrap_or_else(|e| panic!("parse d in {}: {e}", path.display()));
        let _s_str = tokens.next().expect("missing s");
        let a_str = tokens.next().expect("missing a");
        let a: u32 = a_str
            .parse()
            .unwrap_or_else(|e| panic!("parse a in {}: {e}", path.display()));
        let m: Vec<u32> = tokens
            .map(|t| {
                t.parse::<u32>()
                    .unwrap_or_else(|e| panic!("parse m_i in {}: {e}", path.display()))
            })
            .collect();
        out.push(JoeKuoDim { d, a, m });
    }
    out
}

fn emit_constant(out: &mut fs::File, name: &str, dims: &[JoeKuoDim]) {
    writeln!(out, "pub(crate) static {name}: &[JoeKuoD6Dim] = &[").unwrap();
    for dim in dims {
        let m_lits: Vec<String> = dim.m.iter().map(ToString::to_string).collect();
        writeln!(
            out,
            "    JoeKuoD6Dim {{ d: {}, a: {}, m: &[{}] }},",
            dim.d,
            dim.a,
            m_lits.join(", ")
        )
        .unwrap();
    }
    writeln!(out, "];").unwrap();
}
